default_settings: null
behaviors:
  SimpleSkills01:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1638
      buffer_size: 16384
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    checkpoint_interval: 500000
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: match3
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 750000
    time_horizon: 64
    summary_freq: 50000
    threaded: false
    self_play:
      save_steps: 50000
      team_change: 75000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    behavioral_cloning: null
