behaviors:
  POD_01:
    trainer_type: ppo
    summary_freq: 20000
    time_horizon: 128
    max_steps: 5000000
    keep_checkpoints: 5
    even_checkpoints: false
    checkpoint_interval: 20000
    init_path: null    
    threaded: false
    
    hyperparameters:
      learning_rate: 3e-4
      batch_size: 1024
      buffer_size: 4096
      learning_rate_schedule: linear
      beta: 5.0e-3
      epsilon: 0.2
      beta_schedule: linear
      epsilon_schedule: linear 
      lambd: 0.95
      num_epoch: 3
      
      shared_critic: false
      
    network_settings:
      hidden_units: 256
      num_layers: 2
      normalize: false
      vis_encode_type: match3
      goal_conditioning_type: hyper
   
      memory: null
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        
    self_play:
      save_steps: 20000
      team_change: 100000
      swap_steps: 10000
      play_against_latest_model_ratio: 0.5
      window: 10
      
      initial_elo: 1200.0
    behavioral_cloning: null
