behaviors:
  POD_01:
    trainer_type: ppo
    summary_freq: 20000
    time_horizon: 128
    max_steps: 1000000 #changed from 50000000
    keep_checkpoints: 5
    even_checkpoints: false
    checkpoint_interval: 20000
    init_path: null    
    threaded: false
    
    hyperparameters:
      learning_rate: 3e-4
      batch_size: 1024
      buffer_size: 4096
      learning_rate_schedule: linear #changed from constant
      beta: 5.0e-3
      epsilon: 0.2
      beta_schedule: linear #changed from constant
      epsilon_schedule: linear #changed from constant
      lambd: 0.95
      num_epoch: 3
      
      shared_critic: false
      
    network_settings:
      hidden_units: 256
      num_layers: 2
      normalize: false
      vis_encode_type: simple #changed from match3
      goal_conditioning_type: hyper
   
      memory: null
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        
    behavioral_cloning: null